<?xml version="1.0" encoding="utf-8"?><Database Name="Lib_DB" Class="LibraryDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Lib_DB;Integrated Security=True" SettingsObjectName="Linq_to_Library.Properties.Settings" SettingsPropertyName="Lib_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Available" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Return_Date" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Late" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>